[features]
seeds = false

[programs.localnet]
vyper_core = "vyPErCcGJKQQBeeQ59gXcWrDyU4vBrq8qQfacwmsAsp"
rate_mock = "FB7HErqohbgaVV21BRiiMTuiBpeUYT8Yw7Z6EdEL7FAG"
rate_switchboard = "2hGXiH1oEQwjCXRx8bNdHTi49ScZp7Mj2bxcjxtULKe1"
rate_pyth = "3mxtC2cGVhHucUg4p58MVzVqUKLyiy1zWqRkRQdgUBPT"
rate_poolv2 = "5Vm2YZK3SeGbXbtQpKVByP9EvYy78ahnjFXKkf9B3yzW"
redeem_logic_farming = "Fd87TGcYmWs1Gfa7XXZycJwt9kXjRs8axMtxCWtCmowN"
redeem_logic_fila = "9pPodGZL2EWjkj3c7yWjfWrVDfn8Jxss9tEXTEmKLTmM"
redeem_logic_forward = "BrpV1re8MshA8qskKVxcEG8zXG3vf2uLX6myeTKAyhsK"
redeem_logic_lending = "Gc2ZKNuCpdNKhAzEGS2G9rBSiz4z8MULuC3M3t8EqdWA"
redeem_logic_lending_fee = "3mq416it8YJsd5DKNuWeoCCAH8GYJfpuefHSNkSP6LyS"
redeem_logic_vanilla_option = "8fSeRtFseNrjdf8quE2YELhuzLkHV7WEGRPA9Jz8xEVe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# BTC USD Switchboard: https://switchboard.xyz/explorer/3/8SXvChNYFhRq4EZuZvnhjrB3jJRQCv4k3P4W6hesH3Ee
[[test.validator.clone]]
address = "8SXvChNYFhRq4EZuZvnhjrB3jJRQCv4k3P4W6hesH3Ee"

# USDC USD Switchboard: https://switchboard.xyz/explorer/3/BjUgj6YCnFBZ49wF54ddBVA9qu8TeqkFtkbqmZcee8uW
[[test.validator.clone]]
address = "BjUgj6YCnFBZ49wF54ddBVA9qu8TeqkFtkbqmZcee8uW"

# XTZ USD Switchboard: https://switchboard.xyz/explorer/3/F11LACseaLXuRaPSvnD6w15vSPHtx73YaGZv9293rQQm
[[test.validator.clone]]
address = "F11LACseaLXuRaPSvnD6w15vSPHtx73YaGZv9293rQQm"

# BTC USD Pyth: https://pyth.network/price-feeds/crypto-btc-usd
[[test.validator.clone]]
address = "GVXRSBjFk6e6J3NbVPXohDJetcTjaeeuykUpbQF8UoMU"

# SOL USD Pyth: https://pyth.network/price-feeds/crypto-sol-usd
[[test.validator.clone]]
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
